<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Delete-Bin-Trash-PNG-Clipart.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="1.0.0-beta.17" />
    <PackageReference Include="Azure.Identity" Version="1.11.3" />
    <PackageReference Include="Betalgo.OpenAI" Version="8.2.1-beta" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.19" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="OpenAI" Version="1.11.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Delete-Bin-Trash-PNG-Clipart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="AppSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
